
server:
  # 服务端口
  port: 3333



spring:
  config:
    # 引入数据库配置（database-config.yml）
    import: classpath:database-config.yml
  autoconfigure:
    # 禁用 spring-boot 的 security 自动配置，不再生成任何安全密码
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



logging:
  pattern:
    # 控制台中日志的输出格式
    console: "%highlight(%level) %yellow(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green(%logger):%n%msg%n"



mybatis-plus:
  # mapper xml 路径
  mapper-locations: classpath*:team/project/module/**/mapper/*.xml
  global-config:
    # 关闭 mybatis-plus 启动时输出的命令行字符画
    banner: false
  configuration:
    # 关闭下划线命名和驼峰命名的自动转换，必须使用注解指定数据库字段名
    map-underscore-to-camel-case: false
