
# 在这里配置文件存储，然后将文件改名为 file-storage-config.yml
# 在 application.yml 中会引入 file-storage-config.yml

# 为了防止暴露访问阿里云 OSS 的存储空间的 id 和 secret
# 已将 file-storage-config.yml 添加至 .gitignore

file-storage:
  # 本地文件系统
  local-file-system:
    # 存储所有文件和文件夹的根目录，配绝对路径
    root-folder: D:/student-club-management-system
    # 存储“上传的文件”的目录，以根目录为基
    uploaded-files-folder: /upload
    # 标记“上传的文件来自本地服务器”的文件 id 前缀
    uploaded-file-id-prefix: /f
  # 阿里云 OSS（对象存储服务）
  aliyun-oss:
    # 外网访问的地域节点
    endpoint: oss-cn-guangzhou.aliyuncs.com
    # 密钥 id
    access-key-id:      x  # <- 请勿泄露
    # 密钥 secret
    access-key-secret:  x  # <- 请勿泄露
    # 存储空间名称
    bucket-name:        x  # <- 请勿泄露
    # 存储“上传的文件”的目录
    uploaded-files-folder: /upload
    # 标记“上传的文件来自阿里云”的文件 id 前缀
    uploaded-file-id-prefix: /a
